#!/bin/zsh
# research replays, chunked; signals graded in shadow_signals_replay of data/live/replay.duckdb
set -u
cd /Users/personal/Desktop/swing-engine
LOG=data/logs/replay
echo "=== short chunk 1/8 $(date +%H:%M) ==="
uv run swing --settings config/replay.yaml replay --start 2024-10-07 --end 2026-10-05 --no-router --tag nr1 -s apirine_roc_bands,boomers_cooper,chartschool_gap_first_hour,cooper_123_pullback,episodic_pivot,heston_sadka_seasonality,ipo_first_base_breakout,kell_cycle_of_price_action,momentum_burst,pendergast_long_haul,pullback_ema_zone,rsi_divergence,sr_breakout,trendline_break,volatility_expansion_close > $LOG/short_nr1.log 2>&1; echo "exit $? $(date +%H:%M)"; grep -E "Traceback|Error" $LOG/short_nr1.log | tail -3
echo "=== short chunk 2/8 $(date +%H:%M) ==="
uv run swing --settings config/replay.yaml replay --start 2024-10-07 --end 2026-10-05 --no-router --tag nr2 -s avwap_pullback_shannon,breakout_52w,classic_pattern_detector_lmw,darvas_box,expansion_pivot_cooper,hudgin_golden_triangle,katsanos_rsmk,keltner_channel_breakout,momentum_pinball,pendergast_swingthree,pullback_holy_grail,rsi_oversold_macd_confirm,stochastic_pop_and_drop,ttm_squeeze,weinstein_stage2_breakout > $LOG/short_nr2.log 2>&1; echo "exit $? $(date +%H:%M)"; grep -E "Traceback|Error" $LOG/short_nr2.log | tail -3
echo "=== short chunk 3/8 $(date +%H:%M) ==="
uv run swing --settings config/replay.yaml replay --start 2024-10-07 --end 2026-10-05 --no-router --tag nr3 -s base_breakout,bull_flag_breakout,connors_3day_high_low,derrico_price_swing,faber_sector_rotation,ibd_other_bases,katsanos_stiffness,key_reversal_day,moving_momentum_hill,pivot_extension_reversal,pullback_trend,rsi_trend_zigzag_luo,supertrend_flip_strategy,turn_of_month,williams_smash_day > $LOG/short_nr3.log 2>&1; echo "exit $? $(date +%H:%M)"; grep -E "Traceback|Error" $LOG/short_nr3.log | tail -3
echo "=== short chunk 4/8 $(date +%H:%M) ==="
uv run swing --settings config/replay.yaml replay --start 2024-10-07 --end 2026-10-05 --no-router --tag nr4 -s bb_bullish_engulfing_kosinski,calhoun_adx_breakout,connors_hpetf_rsi_variants,donchian_channel_breakout,fibonacci_retracement_pullback,ibs_mean_reversion,katsanos_trend_strength_filters,landry_bow_tie,nr7_nr4_range_contraction,pivot_reversal_breakout,qullamaggie_flag,santa_claus_rally,tac_dmi_trend_start,turnaround_tuesday,wyckoff_spring_accumulation > $LOG/short_nr4.log 2>&1; echo "exit $? $(date +%H:%M)"; grep -E "Traceback|Error" $LOG/short_nr4.log | tail -3
echo "=== short chunk 5/8 $(date +%H:%M) ==="
uv run swing --settings config/replay.yaml replay --start 2024-10-07 --end 2026-10-05 --no-router --tag nr5 -s bollinger_band_mean_reversion,calhoun_atr_high_sma_breakout,connors_pctb,ehlers_dsp_family,full_gap_continuation_bar,ichimoku_cloud_pullback,katsanos_vpn_breakout,last_stochastic_weekly,open_volatility_breakout,point_and_figure_signals,radge_weekend_trend_trader,sentiment_zone_oscillator,td_sequential,turtle_breakout_systems,xs_momentum_rank > $LOG/short_nr5.log 2>&1; echo "exit $? $(date +%H:%M)"; grep -E "Traceback|Error" $LOG/short_nr5.log | tail -3
echo "=== short chunk 6/8 $(date +%H:%M) ==="
uv run swing --settings config/replay.yaml replay --start 2024-10-07 --end 2026-10-05 --no-router --tag nr6 -s bollinger_pctb_mfi_trend,calhoun_four_day_breakout,connors_rsi2_variants,eighty_twenty_reversal,gandalf_project_research_system,industry_momentum_overlay,kaufman_gap_momentum,lizards_cooper,oscillator_cross_family,power_gap,residual_momentum,short_term_reversal_1m,the_anti,turtle_soup,zscore_mean_reversion_garner > $LOG/short_nr6.log 2>&1; echo "exit $? $(date +%H:%M)"; grep -E "Traceback|Error" $LOG/short_nr6.log | tail -3
echo "=== short chunk 7/8 $(date +%H:%M) ==="
uv run swing --settings config/replay.yaml replay --start 2024-10-07 --end 2026-10-05 --no-router --tag nr7 -s bollinger_squeeze_breakout,calhoun_mean_reversion_swing,connors_tps_scale_in,elder_ma_penetration_channel,harmonic_gartley,inside_outside_bar_breakout,kaufman_stress,ma_crossover_family,parabolic_sar_reversal,pre_holiday_effect,rich_simple_trend_channel,slope_performance_trend,three_bar_inside_bar_prathap,vcp_sepa_breakout > $LOG/short_nr7.log 2>&1; echo "exit $? $(date +%H:%M)"; grep -E "Traceback|Error" $LOG/short_nr7.log | tail -3
echo "=== short chunk 8/8 $(date +%H:%M) ==="
uv run swing --settings config/replay.yaml replay --start 2024-10-07 --end 2026-10-05 --no-router --tag nr8 -s bollinger_w_bottom_ii_reversal,cci_correction,consecutive_bars,elder_triple_screen,heikin_ashi_trend_ride,intermarket_divergence_katsanos,kaufman_three_period_divergence,macd_zero_line_swing_points,pe_valuation_reversion,price_zone_oscillator,rsi2_meanrev,sr_bounce,tko_landry,vervoort_heikin_ashi_family > $LOG/short_nr8.log 2>&1; echo "exit $? $(date +%H:%M)"; grep -E "Traceback|Error" $LOG/short_nr8.log | tail -3
echo "=== long chunk 1/8 $(date +%H:%M) ==="
uv run swing --settings config/replay.yaml replay --start 2017-01-01 --end 2024-10-04 --no-router --tag nr1 -s apirine_roc_bands,boomers_cooper,chartschool_gap_first_hour,cooper_123_pullback,episodic_pivot,heston_sadka_seasonality,ipo_first_base_breakout,kell_cycle_of_price_action,momentum_burst,pendergast_long_haul,pullback_ema_zone,rsi_divergence,sr_breakout,trendline_break,volatility_expansion_close > $LOG/long_nr1.log 2>&1; echo "exit $? $(date +%H:%M)"; grep -E "Traceback|Error" $LOG/long_nr1.log | tail -3
echo "=== long chunk 2/8 $(date +%H:%M) ==="
uv run swing --settings config/replay.yaml replay --start 2017-01-01 --end 2024-10-04 --no-router --tag nr2 -s avwap_pullback_shannon,breakout_52w,classic_pattern_detector_lmw,darvas_box,expansion_pivot_cooper,hudgin_golden_triangle,katsanos_rsmk,keltner_channel_breakout,momentum_pinball,pendergast_swingthree,pullback_holy_grail,rsi_oversold_macd_confirm,stochastic_pop_and_drop,ttm_squeeze,weinstein_stage2_breakout > $LOG/long_nr2.log 2>&1; echo "exit $? $(date +%H:%M)"; grep -E "Traceback|Error" $LOG/long_nr2.log | tail -3
echo "=== long chunk 3/8 $(date +%H:%M) ==="
uv run swing --settings config/replay.yaml replay --start 2017-01-01 --end 2024-10-04 --no-router --tag nr3 -s base_breakout,bull_flag_breakout,connors_3day_high_low,derrico_price_swing,faber_sector_rotation,ibd_other_bases,katsanos_stiffness,key_reversal_day,moving_momentum_hill,pivot_extension_reversal,pullback_trend,rsi_trend_zigzag_luo,supertrend_flip_strategy,turn_of_month,williams_smash_day > $LOG/long_nr3.log 2>&1; echo "exit $? $(date +%H:%M)"; grep -E "Traceback|Error" $LOG/long_nr3.log | tail -3
echo "=== long chunk 4/8 $(date +%H:%M) ==="
uv run swing --settings config/replay.yaml replay --start 2017-01-01 --end 2024-10-04 --no-router --tag nr4 -s bb_bullish_engulfing_kosinski,calhoun_adx_breakout,connors_hpetf_rsi_variants,donchian_channel_breakout,fibonacci_retracement_pullback,ibs_mean_reversion,katsanos_trend_strength_filters,landry_bow_tie,nr7_nr4_range_contraction,pivot_reversal_breakout,qullamaggie_flag,santa_claus_rally,tac_dmi_trend_start,turnaround_tuesday,wyckoff_spring_accumulation > $LOG/long_nr4.log 2>&1; echo "exit $? $(date +%H:%M)"; grep -E "Traceback|Error" $LOG/long_nr4.log | tail -3
echo "=== long chunk 5/8 $(date +%H:%M) ==="
uv run swing --settings config/replay.yaml replay --start 2017-01-01 --end 2024-10-04 --no-router --tag nr5 -s bollinger_band_mean_reversion,calhoun_atr_high_sma_breakout,connors_pctb,ehlers_dsp_family,full_gap_continuation_bar,ichimoku_cloud_pullback,katsanos_vpn_breakout,last_stochastic_weekly,open_volatility_breakout,point_and_figure_signals,radge_weekend_trend_trader,sentiment_zone_oscillator,td_sequential,turtle_breakout_systems,xs_momentum_rank > $LOG/long_nr5.log 2>&1; echo "exit $? $(date +%H:%M)"; grep -E "Traceback|Error" $LOG/long_nr5.log | tail -3
echo "=== long chunk 6/8 $(date +%H:%M) ==="
uv run swing --settings config/replay.yaml replay --start 2017-01-01 --end 2024-10-04 --no-router --tag nr6 -s bollinger_pctb_mfi_trend,calhoun_four_day_breakout,connors_rsi2_variants,eighty_twenty_reversal,gandalf_project_research_system,industry_momentum_overlay,kaufman_gap_momentum,lizards_cooper,oscillator_cross_family,power_gap,residual_momentum,short_term_reversal_1m,the_anti,turtle_soup,zscore_mean_reversion_garner > $LOG/long_nr6.log 2>&1; echo "exit $? $(date +%H:%M)"; grep -E "Traceback|Error" $LOG/long_nr6.log | tail -3
echo "=== long chunk 7/8 $(date +%H:%M) ==="
uv run swing --settings config/replay.yaml replay --start 2017-01-01 --end 2024-10-04 --no-router --tag nr7 -s bollinger_squeeze_breakout,calhoun_mean_reversion_swing,connors_tps_scale_in,elder_ma_penetration_channel,harmonic_gartley,inside_outside_bar_breakout,kaufman_stress,ma_crossover_family,parabolic_sar_reversal,pre_holiday_effect,rich_simple_trend_channel,slope_performance_trend,three_bar_inside_bar_prathap,vcp_sepa_breakout > $LOG/long_nr7.log 2>&1; echo "exit $? $(date +%H:%M)"; grep -E "Traceback|Error" $LOG/long_nr7.log | tail -3
echo "=== long chunk 8/8 $(date +%H:%M) ==="
uv run swing --settings config/replay.yaml replay --start 2017-01-01 --end 2024-10-04 --no-router --tag nr8 -s bollinger_w_bottom_ii_reversal,cci_correction,consecutive_bars,elder_triple_screen,heikin_ashi_trend_ride,intermarket_divergence_katsanos,kaufman_three_period_divergence,macd_zero_line_swing_points,pe_valuation_reversion,price_zone_oscillator,rsi2_meanrev,sr_bounce,tko_landry,vervoort_heikin_ashi_family > $LOG/long_nr8.log 2>&1; echo "exit $? $(date +%H:%M)"; grep -E "Traceback|Error" $LOG/long_nr8.log | tail -3
echo ALL DONE
